// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Dir(arg1) {
  return window['go']['dialog']['Dialog']['Dir'](arg1);
}

export function OpenDirectory(arg1) {
  return window['go']['dialog']['Dialog']['OpenDirectory'](arg1);
}

export function OpenFileDialog(arg1) {
  return window['go']['dialog']['Dialog']['OpenFileDialog'](arg1);
}

export function PathJoin(arg1) {
  return window['go']['dialog']['Dialog']['PathJoin'](arg1);
}

export function ShowErrorDialog(arg1) {
  return window['go']['dialog']['Dialog']['ShowErrorDialog'](arg1);
}
