// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {frontend} from '../models';

export function Dir(arg1:string):Promise<string>;

export function OpenDirectory(arg1:frontend.OpenDialogOptions):Promise<string>;

export function OpenFileDialog(arg1:frontend.OpenDialogOptions):Promise<string>;

export function PathJoin(arg1:Array<string>):Promise<string>;

export function ShowErrorDialog(arg1:string):Promise<void>;
