// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {file} from '../models';

export function ErrorLog(arg1:Error):Promise<void>;

export function GetFileInfo(arg1:string):Promise<file.FileInfo>;

export function GetFilesInfo(arg1:Array<string>):Promise<Array<file.FileInfo>>;

export function LocalOpenFile(arg1:string):Promise<void>;

export function LocalOpenFolder(arg1:string):Promise<void>;

export function ReadFile(arg1:string):Promise<string>;

export function WriteFile(arg1:string,arg2:string):Promise<void>;
